import { __makeTemplateObject, __assign, __awaiter, __generator, __rest } from 'tslib';
import styled, { css, StyleSheetManager } from 'styled-components';
import React, { useRef, useState, useLayoutEffect, useEffect, useContext, useCallback } from 'react';
import classnames from 'classnames';
import { PrismLight } from 'react-syntax-highlighter';
import js from 'react-syntax-highlighter/dist/esm/languages/prism/javascript';
import jsx from 'react-syntax-highlighter/dist/esm/languages/prism/jsx';
import ts from 'react-syntax-highlighter/dist/esm/languages/prism/typescript';
import tsx from 'react-syntax-highlighter/dist/esm/languages/prism/tsx';
import prism from 'react-syntax-highlighter/dist/esm/styles/prism/prism';
import { Grid, Icon, Balloon, Card, Table as Table$1 } from '@alicloud/console-components';
import { createPortal } from 'react-dom';
import unified from 'unified';
import parse from 'remark-parse';
import remark2rehype from 'remark-rehype';
import rehype2react from 'rehype-react';
import rehypeRaw from 'rehype-raw';
import rehypeSanitize from 'rehype-sanitize';
import defaultSanitizeConfig from 'hast-util-sanitize/lib/github.json';
import { MDXProvider } from '@mdx-js/react';
import debounce from 'lodash.debounce';
import isequal from 'lodash.isequal';